line-length = 88
target-version = "py38"

[lint]
select = ["E", "F", "I", "B", "UP", "C4", "SIM"]
ignore = ["E501"]  # Since black already has line length enforcement, ignoring this so it's not redundant

[format]
quote-style = "double"
